### ISSUE TITLE
Create sign-in page

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#1]
As a user, I need to be able to enter the username and password provided by my coach.
As a user, I want the app to remember me.

We will accomplish this by getting the username and password from the CSV file of data, put it into our database, and the app will validate against this data in our database.  

The sign in page will not have a registration button, that can only be done by the user meeting with their coach and the coach entering it into their Tracker.

**Comment by doub1ejack** [comment]
I can't tell what PR implemented this, but a user can now log in if the credentials exist in Firebase so this issue is done.
