### ISSUE TITLE
Implement loading page during login and profile load

### ISSUE THREAD

**Issue by jfenner** [codeforbtv/cvoeo-app#104]
During application startup, the login page is displayed temporarily before the user logs in.  If the user is already registered and not logging in then the page should either be hidden or disabled.

Also, when the dashboard is loading the goalArray information, a transparent "loading" page should be displayed.

**Comment by jfenner** [comment]
Per @johnneed, this can be fixed by using redux-persist.

**Comment by johnneed** [comment]
This fixed with the addition of a persistent store
