### ISSUE TITLE
Emails should have a real "from" address

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/cvoeo-app#159]
Currently the emails that are sent to a user from the "register" or "forgot password" links have a generated firebase email that looks pretty spammy.

Let's figure out how to change these and use (for the time being) the `momm@codeforbtv.org` email address.

![image](https://user-images.githubusercontent.com/1809882/68089263-0315e880-fe35-11e9-9f81-347f580d1125.png)

**Comment by mpettit** [comment]
This can be done in the firebase console. Someone has already changed to noreply@codeforbtv.org
