### ISSUE TITLE
Create expandable components

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/cvoeo-app#19]
The sections for Appointments, Current Goals, and Completed goals all use basically the same component.  We need to find an expandable component and make sure it has a place for a label and a show/hide toggle.
<img src="https://user-images.githubusercontent.com/1809882/48041149-f095a000-e149-11e8-942e-2ab2f555090b.png" width="250" />
(See [InVision for most current wireframes](https://projects.invisionapp.com/share/9GOV7CKW53U#/screens).)

**Comment by doub1ejack** [comment]
I think @jbpayne has worked this out.  See issue #17

**Comment by kmeyersvt** [comment]
@doub1ejack  so can this be closed as a duplicate?

**Comment by jbpayne** [comment]
All expandable components are now working
