### ISSUE TITLE
Create interface from Outcome Tracker Database to Money on my Mind Database

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#2]
Outcome Tracker will provide a feed in the form of a CSV file. Right now, the plan is that it will be created hourly on their SFTP server and we will grab it.

This ticket is to determine the best mechanism to grab the data and put it into our database. Currently, we are considering:
- ETL package with cron job
- conversion software that creates an API from a CSV file, we can then consume the API

**Comment by kmeyersvt** [comment]
@doub1ejack  is this still needed? I thought you had set something up  to get data from  their files?

**Comment by iritush** [comment]
Created branch 'connect-to-cvoeo-sftp-from-fb-function' to work on this issue

**Comment by iritush** [comment]
-An sftp server was set by cvoeo and access was given to the code for btv team
-csv files representing the desired data from the outcome tracker database are periodically created, zipped and copied over to this sftp server by the cvoeo team.

I am going to create separate issues to track pulling data from the sftp server using firebase functions, parsing it and inserting it to the firebase DB
