### ISSUE TITLE
DRAFT: Show appointment reminders in the top segment of the screen

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#28]
GOAL: As a user, I want to receive reminders of upcoming appointments and classes.
WHY:  This is one of the primary purposes of this app.
Definition of Done: 
- Appointments coming from Outcome Tracker show in the top component area of the home screen
- Upcoming classes show in the top component area of the home screen

TBD: we don't know yet what this data is going to look like so I can't be more specific.

**Comment by jbpayne** [comment]
Upcoming events are now populating from firestore -> user -> upcomingArray
