### ISSUE TITLE
Define data models to be used by the app.

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/cvoeo-app#3]
We need data models, indicating fields and types  for all the domains to used by the app.

e.g.  A User model might look thusly: 

User : {
   id : string,
   firstName: string,
   lastName: string,
   dateOfBirth : Date,
   balance:  Number
}

**Comment by doub1ejack** [comment]
At this point, it looks like it will be harder to predefine the data models than it will be to iterate over them.  

@jbpayne  has been building up sample data models in the test@example.com use in Firestore as he works on the dashboard, and this seems like a pretty good way to start deciding what data we will ultimately need.
