### ISSUE TITLE
Create new header image with CVOEO and MoMM logos

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#30]
Goal: to have a new header image that combines the CVOEO and MoMM logos
Why: because we love our new logo and this is how we want to brand it
Definition of Done: 
- The header image exists and is attached to this ticket and ready to insert into the app.

**Comment by siuanm** [comment]
![momm_landingv2](https://user-images.githubusercontent.com/38860905/49813602-ca10e900-fd35-11e8-9418-2ffca65266e9.png) Does this work?

**Comment by kmeyersvt** [comment]
I think this looks great!

**Comment by siuanm** [comment]
Super! I will upload some more static assets then.

**Comment by siuanm** [comment]
![logo_w_cvoeo](https://user-images.githubusercontent.com/38860905/49819357-347c5600-fd43-11e8-9b0c-353a5eb1c578.png)

**Comment by kmeyersvt** [comment]
Client wants us to use their moneybrain.jpg file instead of the pig. Also, their Financial Futures logo instead of the CVOEO logo.  All collateral in Drive in the Design Materials folder.

**Comment by siuanm** [comment]
![group 1](https://user-images.githubusercontent.com/38860905/50969785-900a4280-14ad-11e9-9984-e8bfde969feb.png)
![moneyonmymind](https://user-images.githubusercontent.com/38860905/50969795-939dc980-14ad-11e9-8337-d2284240f64d.png)
I will put these on google drive also

**Comment by doub1ejack** [comment]
Ok, with these two images available on the Team Drive, I think this story is resolved.
