### ISSUE TITLE
Restyle the Forgot Password screen

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#32]
This issue is very similar to #31: we need to restyle the forgot password screen to match the login screen design (below).  There are some minor differences from the Login screen design:

1. We want to keep the current stack navigation that returns user to the login screen.
2. The form on the forgot password screen should stay as-is.

| current "Forgot Password" screen | intended Login screen |
|---|---|
| <img src="https://lh3.googleusercontent.com/lye1kgQNlG_CI9i7L2DgF18XdjF-M_RONfGlS55C0sUeDrkmkn1UG1knzft0Ibzlus8OVQgUxf9fmE5o4_BirK7IUY2CizYl19cdg065zNKM6rcwtUjgWQySP-yXDBmHrfp99spXrhxMXzXvqHjbA-aaZ62ZY8YNcQ3BsjB3eGxNLKRwYBsfH-S2Y2IhI888mO3JqCX_ZusgWHUHnnW7APWYZ0iNGyglLbt5T0_-1RuoXAnL00Jk1Mep3jA_8zGA3Pss8l1TOG1pXAb9QINq5MrrIVc4EwZBoAwTdd7Yddvn8x0OXFaw2C6d09h2_sirGOTLuJT_ODUnC2l3gN5-EZGZoeNbcEDOy1YTwXg8DoODihKJ8f9SLa6TrO5Bz9BwKi3AQizluqOE4oJ_OtG8soYuw-pLUBLgkkUUc-JBahUp2FdmszOCkzCYga_7yycXqy-VKsJWRtjp0l70-rjznILceS58y55GHq5rZUnvdaN-HMEAMGj3u0XogU-HpLiuMACS_efEAWjc9lf7KCLfmVNsOBlch78M4erJjz8hiEcijbPn_o2-mVFHIGGVkvueNubCh3mrN6rog8falZPFVP70fcbTuLOpbapyRpLabyFm8pftA3C8M97sotZsvuWQj7v12INNGHzOwqRFEUk83ntElFlBbUMfTWnsrSPELtkoJRVHlGJuN7RJ68ZCwaBDzyxkolVaWQiQyP_9UrM=w405-h718-no" width=200> | <img src="https://user-images.githubusercontent.com/38860905/51055045-ad720600-15ac-11e9-9760-8881b372ffc9.png" width=200>|

Resources needed should be on [the Team Drive](https://drive.google.com/drive/u/2/search?q=type:image%20parent:1KdC_iNceHcSPv8EPmJReyZeforcQULnO), including 

* moneyOnMyMind.png
   <img src="https://lh6.googleusercontent.com/XjK9-ZScUqNeCe3eWEQdHcFxZ5ZfHRKFcxDRgunBiHf85d-3JkBYpGlRiQPZBvJgVtLeD7UnnxZQNg=w1439-h766" width=150>
* LandingPageImage.jpg
   <img src="https://camo.githubusercontent.com/6e82168a8d0b27e916ad4c539cfb4af1c1beab06/68747470733a2f2f6c68342e676f6f676c6575736572636f6e74656e742e636f6d2f5f336f3939612d31356b7a6455704b50696b7135394f6a3636427a6a6d69774c4c526a504b4a59306f38527146547948316e7175563266365f766470336f504563734d73594547414371684f43413d77313433392d68373636" width=150>
* [style guide](https://drive.google.com/open?id=1YVusLfBxnMZOL84CU9dhyH0PpHFqH6ph) with color codes

**Comment by doub1ejack** [comment]
@siuanm Can you describe how you want the login screen to look?  You can just update the issue description above.

**Comment by jbpayne** [comment]
@doub1ejack Did you mean the Forgot Password screen?  If so, @siuanm should
it look the same as the login screen for consistency, or is it an
opportunity to use design A from the login screen options?

**Comment by doub1ejack** [comment]
@jbpayne Yeah, I meant the forgot password screen.

@siuanm I'm just going to assume that this screen should be visually similar to the Login Screen.  I'll update the issue description accordingly, and you can correct me if I'm wrong.

**Comment by siuanm** [comment]
This is what I have for forgot password screen (though still revisiting the "momm" logo for here and dashboard) : ![android 6 24 1](https://user-images.githubusercontent.com/38860905/51076168-fa181880-1662-11e9-999b-08470d952176.png)

**Comment by jbpayne** [comment]
Siuan put this in Slack yesterday

**Comment by jbpayne** [comment]
Looks like we replied at the same time

**Comment by jbpayne** [comment]
See https://github.com/codeforbtv/cvoeo-app/pull/52
