### ISSUE TITLE
Insert new header image on main screen

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#33]
When #30 is complete, insert the new image into the header of the main screen.

**Comment by doub1ejack** [comment]
I think this is done.

@kmeyersvt & @siuanm, this is the current version of the dashboard screen.  Does this resolve this issue?

![image](https://user-images.githubusercontent.com/1809882/51046516-421c3a00-1594-11e9-8bc9-bb2c6453785d.png)

**Comment by siuanm** [comment]
If main screen means dashboard, this looks done. I thought this task was about the landing page (#30 shows the landing page.)

**Comment by kmeyersvt** [comment]
I didn't realize that we were abbreviating momm for the end user? I'm not sure it works in that way. To me it looks like a kid whining at their mother.

**Comment by jbpayne** [comment]
This is what it would look like spelled out

**Comment by siuanm** [comment]
@kmeyersvt That's hilarious! I can mockup a couple of other ideas. I think writing out the full "money on my mind" looks very long for that space, especially when the time comes to add a hamburger and ellipsis. Maybe just the financial futures logo would work, or I can try scaling down their head/brain image to a super small size. I will mock-up some possibilities for you to look at.

**Comment by kmeyersvt** [comment]
Thank you, Siuan. I agree that the full title is too long too. Hopefully the logo will scale. Or maybe the financial Futures logo?
