### ISSUE TITLE
Lay Out Current Goals Segment

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#34]
Goal: As a User, I want to know what goals I currently have set.  And if I have no goals, I want to be aware that I should set some.
Why: We need to reminder users of the goals they are working on
DoD:
- If there are no goals, display a message "Let's work together on some goals to move you forward. Schedule an appointment with your counselor today!"
- If there is one goal, it displays fully in the Goals panel.
- If there is more than one goal, the rest are displayed when the section is expanded
- There is a visual indicator that there are more goals available (this should be a standard indicator like highlighting the down arrow)

**Comment by kmeyersvt** [comment]
@siuanm  When you're working on the CSS, I'm thinking we should include something to highlight the expansion icon to indicate that there is more to see?

**Comment by kmeyersvt** [comment]
Unblocking because the client has approved the UI design.

**Comment by doub1ejack** [comment]
@jbpayne I think you've done this.  Can you confirm & resolve this issue?
