### ISSUE TITLE
Add a Logout link to the ellipsis menu

### ISSUE THREAD

**Issue by jbpayne** [codeforbtv/cvoeo-app#37]

**Comment by jbpayne** [comment]
We probably do need the ubiquitous hamburger menu, and I'm happy to add one
if needed.  Currently the logout button is just for development, and,
ideally, logout would never need to be used in this app, although it's good
practice to have a logout when there's a login.  I guess we should discuss
what other items would go on a hamburger menu, like account, settings,
etc., with the understanding that there's a large amount of basic
functionality to implement first.

**Comment by kmeyersvt** [comment]
I'll make a ticket for it. We also need change  password.

**Comment by doub1ejack** [comment]
If the only special action is logging out, it's possible that that could be an admin-only feature if Siuan doesn't want to complicate the design.  Most users will never want to log out.  On the other hand, if there are other app administration features that will be added in also (notification settings come to mind), then we probably will need some kind of menu nav for them. 

Make sure we include @siuanm in on these design conversations; she'll have good input.

**Comment by kmeyersvt** [comment]
Users are likely going to want to change their password since it's provided by their coach.

**Comment by doub1ejack** [comment]
@jbpayne, if you want to try building out the functionality, you can do that any time.  As a temporary solution to allow you to continue workng on the loging screen, you could just add it as a button at the bottom of the dashboard.  Later on we can move the button elsewhere, or hide it for non-admins or whatever we decide we want to do.

**Comment by siuanm** [comment]
So, I am working on the dashboard at the moment and though these are not the final colors, I had included the possibility of a hamburger and "more" icon in the top toolbar, where additional functionalities could be kept. It could be where logging out, profile information or changing the password are kept for now. 
![android](https://user-images.githubusercontent.com/38860905/50354626-259f5b80-051a-11e9-9d9c-58f087bbfa13.png)

**Comment by jbpayne** [comment]
Looks good to me.  They're fairly standard navigation, so it makes a lot of
sense.

**Comment by doub1ejack** [comment]
@jbpayne (or anyone else who wants to work on this), if you're not sure how to add sidebar or stack navigation to the app, I recommend taking a look at the first week or two of the coursera react native class.  You could probably figure it out more quickly from reading blogs & docs, but the coursera course will give you a good understanding of how the navigation works and what the standard nav types are.
https://www.coursera.org/learn/react-native/home/week/1

**Comment by doub1ejack** [comment]
This issue is blocked by #40.

**Comment by jbpayne** [comment]
Logout link added to the ellipsis alert modal (currently standing in for a menu):

https://github.com/codeforbtv/cvoeo-app/pull/49

**Comment by kmeyersvt** [comment]
@jbpayne  Is this really done? I'm  not  sure  what automation would have moved this to Done if it was blocked?
