### ISSUE TITLE
Add a "3 dot" (ellipsis) menu to the dashboard

### ISSUE THREAD

**Issue by jbpayne** [codeforbtv/cvoeo-app#40]
As a user, I want to click the ellipsis icon in the top-right corner of the dashboard and have a menu of account options so that I can manage my account

**Comment by doub1ejack** [comment]
@siuanm Do you have a preference of which type of navigation we should put the logout button under?  The two options I see right off are....

1) stack nav (switching to an entirely new screen):
<img src="https://i.stack.imgur.com/25MyO.jpg" width=500>

2) sidebar nav 
<img src="https://i.stack.imgur.com/9UVxI.png" width=250>

**Comment by siuanm** [comment]
@doub1ejack I am only seeing this message now. I am so sorry I never responded! I personally like the sidebar nav better for something like this. It would not be my preference to switch to a whole new screen

**Comment by kmeyersvt** [comment]
Siuan's demo has the bubble side menu template coming from the right. Can we do that?

**Comment by kmeyersvt** [comment]
mockup is  here in Drive:
https://drive.google.com/drive/folders/10RxdZp7gw_oQeayuoLf7T58yZIcXpn0N

**Comment by johnneed** [comment]
I think this ticket is complete.  This is the current menu when clicking the ellipse.
![image](https://user-images.githubusercontent.com/1043179/63904229-4770ac80-c9de-11e9-8a39-083896e51d20.png)
@jbpayne  @doub1ejack or @jfenner Can you confirm this?  If so this issue should be closed.

**Comment by jbpayne** [comment]
I agree. Closing the issue.
