### ISSUE TITLE
Update the app icon

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/cvoeo-app#42]
The logo for the app is defined in app.json.  This logo is used by expo and by iOS & Android as the app icon.  We need to update it for the new MoMM design.  

Currently, we are using a placeholder logo from before the design work really started.  This should be replaced with `app icon.png` in the "[cvoeo/images](https://drive.google.com/drive/u/2/folders/1TqI2l3kfo6NvGTmmgA0DZVNR-pA7MlPZ)" folder on the Team Drive.

| current icon | new `app icon.png`|
|-------------|----------|
| <br><img src="https://user-images.githubusercontent.com/1809882/51075691-3d6f8880-165d-11e9-8347-a0bd20103c8b.png" width=200> | <img src="https://lh5.googleusercontent.com/vJBKnEa_-v8-TCbFY6q-0-6KVTGbmtwjq5JB_kn8BFtyW7DruL8GUxfqZiNi8Gx1sGPKJXDvJawKVg=w1439-h766-rw" width=75>

**For guidance** on how to make this change, you can use [this closed (unmerged) pull request](https://github.com/codeforbtv/cvoeo-app/pull/23).  It does the exact work this issue needs, except it used the old, beloved moneyPig image for the icon.

**To test your work**,  it's probably easiest to publish the app to your own expo account.  [Read the docs](https://docs.expo.io/versions/latest/workflow/publishing#how-to-publish) for directions.  After publishing your test branch with the updated logo, you should see the app in the list of projects in the expo app on your phone.  When you open the CVOEO project, you should see your new logo instead of the one in the screenshot above.

| <img src="https://user-images.githubusercontent.com/1809882/51075758-05b51080-165e-11e9-9cdf-e95ffea5c785.png" width=200> |
|---|

**Comment by doub1ejack** [comment]
@siuanm When you have time, could you provide a 1024x1024 image of whatever you like for the icon?  The expo [icon best practices doc](https://docs.expo.io/versions/latest/guides/app-icons#icon-best-practices) is a helpful reference (for me at least).  Unless you feel strongly about different icons for iOS/Android right now, we can just use one icon for both.

**Comment by siuanm** [comment]
I will get you one this weekend. (I don't think there needs to be different icons)

**Comment by doub1ejack** [comment]
Yep, go for it.
Assign this issue to yourself and ask any implementation questions back in the slack channel.

**Comment by krittiyaclark** [comment]
How to assign it to me?

**Comment by kmeyersvt** [comment]
@krittiyaclark The beginning of this ticket has a link to the Google Drive where this image is stored. Please click that link and get the "app icon.png" file (it looks like the one that Siuan has in her comment above. That is the icon that should be used.

**Comment by jbpayne** [comment]
You can either rename the file to match the existing /assets/images/icon.png, or if you simply copy the file to /assets/images, then change line 13 of app.json to point it to the new file.

**Comment by krittiyaclark** [comment]
I can not access Google drive but I save the image from here. I already pushed it. Please, anyone review if it correct.
