### ISSUE TITLE
Create & deploy hello-world firebase function

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/cvoeo-app#57]
The first step in using a function to update the app data is learning how to use firebase functions.  

- check out a new branch
- Add a simple function to the [\functions](https://github.com/codeforbtv/cvoeo-app/tree/master/functions) directory
- create a pull request that 
   - request at least 1 reviewer
   - has a description that will make sense to other teammates
   - references this issue number in the description
- deploy to firebase 
- verify the success of your function and add a comment to the PR explaining the results

**Comment by kmeyersvt** [comment]
@jbpayne  why did you move this to Needs Review? What else is needed? I  thought this was Irit's practice task?

**Comment by iritush** [comment]
This was reviewed and merged. Closing

**Comment by kmeyersvt** [comment]
This is still in Needs Review. Should it be closed, @iritush ?

**Comment by iritush** [comment]
This is done: https://github.com/codeforbtv/cvoeo-app/pull/58
