### ISSUE TITLE
User can mark goal Submitted

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#63]
**User Story:** As a user, I want to mark a  goal complete so that it's added to my completed list and I stop getting notifications

**Definition of Done**
- Clicking the Complete checkbox changes the button to look like the mockup:
https://drive.google.com/drive/folders/10RxdZp7gw_oQeayuoLf7T58yZIcXpn0N
    <img src="https://i.gyazo.com/e9ff8eb34215976563a5385f065c7e86.gif" width="250px" />

- The checked icon persists on the goal
- The goal moves to the Submimtted  panel
- Message displays  to the user "Congratulations on  achieving your goal. Be sure to  let your coach know the next time you meet!"
- Throws the goal completion party screen.
- Completed field in the database is updated with the date/time

**Comment by doub1ejack** [comment]
The bulk of this issue is addressed by #111.  I'll split this off into a few subsequent issues.
