### ISSUE TITLE
Fix speedometer on iOS

### ISSUE THREAD

**Issue by jbpayne** [codeforbtv/cvoeo-app#69]
The speedometer graph uses an SVG Group which is rotated to visualize the progress toward completion.  This works correctly on Android, but on iOS the `Svg.Rect` under `Svg.G` does not rotate with the rest of the group, changing its `x` offset depending on the rotation value assigned.

**Comment by jbpayne** [comment]
Please see https://github.com/codeforbtv/cvoeo-app/pull/71

**Comment by doub1ejack** [comment]
Merged #71
