### ISSUE TITLE
Forgot password screen

### ISSUE THREAD

**Issue by johnneed** [codeforbtv/cvoeo-app#8]
Add a new forgot password screen that works with firebase's built in password reset functionality.

there is a link to this missing screen on the login screen.

**Comment by kmeyersvt** [comment]
I'm not 100% sure on this one.  My understanding was that the un and pw were coming from the coach.  Though I guess it doesn't have to stay in sync with Call Tracker?

**Comment by johnneed** [comment]
Currently there's no way for anyone to create their own account, it will have to created by the coach.

However, if we don't have reset password functionality, then the coaches will be responsible for that and the inconvenience of recovering a lost password will be too burdensome for most folk.

Allowing users to reset their password won't affect coach's access to the data.

IMHO password reset should be a feature

**Comment by kmeyersvt** [comment]
Yes, that makes sense. I'll add it to the use cases.

**Comment by kmeyersvt** [comment]
Yes, that makes sense. I'll add it to the use cases.
