### ISSUE TITLE
New "GoalDetail" screen

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/cvoeo-app#85]
When a user wants to snooze goal notifications or mark a goal as complete, instead of trying to do it through a dropdown or a modal screen, let's just load a new screen. 

For this task, 
 - [ ] a new screen component should be created
 - [ ] user should click a goal on the dashboard and navigate to this screen
 - [ ] new screen should have a back button to return to the dashboard

**Comment by sjv01180** [comment]
May I be assigned to this issue?

**Comment by doub1ejack** [comment]
@sjv01180 I was chatting with Katrina recently and she had a great point about the goal details. It would be nice to keep them available on the dashboard instead of going to a new screen because this would be the only other screen in the app. Consistency is nice so keeping that in the dashboard component is better. I'll follow up with you on this tonight.
