### ISSUE TITLE
Add an expandable goal detail component to the goal component.

### ISSUE THREAD

**Issue by doub1ejack** [codeforbtv/cvoeo-app#87]
A component that will wrap the interactive goal detail fields. This issue should:
- Make a modal that is opened when the user taps a non-complete goal or when tapping the goal in a  push notification
The main screen would only show the goal name, tapping anywhere in  the  box opens the  modal.
- [ ] Stub out the rough location of future form elements
- [ ] Indicate that there are details
This should show the goal and  allow you to get to details instead of having the  reminder and Completed icon on the main screen.
![image](https://user-images.githubusercontent.com/37085086/62172151-542ab380-b2ff-11e9-91df-b2aa0eecdeca.png)
-  Remind me
- [ ] Have a "Done" button
- [ ] Open when triggered by tapping the goal or by tapping the push notification
- [ ] Close when the Done button is pressed

https://drive.google.com/drive/u/0/folders/1y34MjHpjr0SBSRsbQ_h2Zepfzt9gs9uQ this shows  the dropdowns  in  the pane which was the design, but we need to move this action to when you tap on it to have the modal open to set the interval or mark something complete.

![image](https://user-images.githubusercontent.com/37085086/62985087-adb4d700-be03-11e9-9dc9-bea464679153.png)

**Comment by sjv01180** [comment]
I cannot assign myself onto this issue because I haven't been added to the Code for BTV group, or I lack the permission to do so. Could you modify my permissions in this repository?

**Comment by kmeyersvt** [comment]
@sjv01180 I edited this description at Hack Night based on a discussion with Mike Pettit and Micah and I think I may have changed the essence of the ticket. What have you done on this so far? If it was just to create the expandable container, then I'll move my changes in the description  to a new ticket.

The component to show one vs all is already there, so if you could let us know  what you have been working on in that ticket, please tag us or hit it up in Slack

**Comment by jfenner** [comment]
Proposing a change to the way goals are stored in the firebase database.  Currently a goal is either in progress (open) or complete based on the "complete" field. 

I'm proposing removing the "complete" field and adding a "status" field with possible values of "open", "submitted", or "complete".  This will expand so we can have a submitted status and make the goal stateful.

Only downside I know will require a change to the populating function when it parses the CSV file and updates the database.

**Comment by johnneed** [comment]
Hey @jfenner I just finished #92 .

It just occurred to me that we have some conflicting specs where.  

92 requires these controls to be in a separate modal, but your ticket has the controls on the dashboard.

I probably probably stomped some of your code because of this.  

We should get some clarity on how the user is supposed to snooze goals and mark them as complete.

@kmeyersvt Please have look at #92 and this ticket

**Comment by doub1ejack** [comment]
This issue is largely addressed by #111.  I'll open another issue for an item related to this PR though.
