### ISSUE TITLE
Login page: add padding to left side of login fields 

### ISSUE THREAD

**Issue by kmeyersvt** [codeforbtv/cvoeo-app#97]
Found on Samsung Galaxy S9. Please check Apple.

The username and password are crammed into the curve of the un/pw fields.  Please add a few spaces of left padding to make your typing start where the oval squares up.

![Screenshot_20190813-190339_Expo](https://user-images.githubusercontent.com/37085086/62983487-78a58600-bdfd-11e9-9c92-185ba16cabb7.jpg)

**Comment by johnneed** [comment]
Fixed with a previous merged
